### PR TITLE
[ WIP ] Added basic check to exit given no sass path

### LINKED ISSUE #91: Unable to handle modules without sass.
As pointed out in #79 `pancake` and in particular `pancake-sass` haven't been properly tested with modules that don't need sass. 

Issue should be around here: https://github.com/govau/pancake/blob/master/packages/pancake-sass/src/pancake.js#L110

### PR DESCRIPTION
**Pull request by adamzerella**
Fix #91 

- Add test for module with no sass, only js - seems to pass but could be false positive?

### CODE REVIEW

**Comment by adamzerella** [comment]
@alex-page Yeah this is the way the tests are setup. Each test has a lot of files in it :\

**Comment by alex-page** [comment]
You should not of changed every test file that many times look at this feature change:
https://github.com/govau/pancake/pull/87

**Comment by adamzerella** [comment]
I added a new test called `test15/` with the relevant files...?

**Comment by alex-page** [comment]
Yeah I get that homie but why is it so large? Does the test need to be 18k lines?

**Comment by adamzerella** [comment]
After more digging it appears that tweaking pancake isn't actually required. The problem that started this PR and #91 was the thought that pancake can't handle a sass dependant component that requires a non-sass dependant component, this doesn't seem to be true.

What is required though is the `pancake.sass` key be set with `'name': false` correctly on the non-sass dependant component.

We should still add a test for this specific case but it turns out pancake actually handles this correctly.

**Comment by adamzerella** [comment]
Closing this in favour of #93

**Pull request closed without merging**
